version: '3.9'

services:
  # Service for building the React app
  frontend-build:
    react_frontend:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: yarn build
    working_dir: /app
    environment:
      NODE_ENV: production
    # depends_on:
    #   - yarn-cache

  # Service for serving the React app during development
  fontend-dev:
    react_frontend:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: yarn dev
    working_dir: /app
    ports:
      - "3000:3000"
    # depends_on:
    #   - yarn-cache

  # Service for caching Yarn packages to speed up builds
#   yarn-cache:
#     image: node:18.17.0-alpine3.17
#     volumes:
#       - yarn-cache:/usr/local/share/.cache/yarn/v6

# volumes:
#   yarn-cache:
  
    